---
abstract: 'SmokeBox helper module to determine perl version'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SmokeBox-PerlVersion
requires:
  IPC::Cmd: 0
  POE: 1.293
  POE::Quickie: 0.11
  perl: 5.006002
resources:
  homepage: http://github.com/bingos/app-smokebox-perlversion/tree
  repository: git://github.com/bingos/app-smokebox-perlversion.git
version: 0.04
